# This is a template - replace with actual sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: branch-manager-secrets
  namespace: branch-manager
  labels:
    app: branch-manager
    app.kubernetes.io/name: branch-manager
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Replace these with actual values or use external secret management
  database-url: "postgresql://username:password@host:5432/production_db"
  api-key: "your-super-secure-api-key-here"
  
# Alternative: Use SealedSecrets
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: branch-manager-secrets
#   namespace: branch-manager
# spec:
#   encryptedData:
#     database-url: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
#     api-key: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...