apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: branch-manager
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DB_PREFIX
          value: "staging_"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"