apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: branch-manager-staging

namespace: branch-manager

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: ghcr.io/chad3814/postgres-branch-manager
    newTag: staging-latest

commonLabels:
  environment: staging
  
replicas:
  - name: branch-manager
    count: 1