apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: branch-manager-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: branch-manager
    app.kubernetes.io/component: application
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: branch-manager
  
  source:
    repoURL: https://github.com/chad3814/branch-manager-config.git
    targetRevision: main
    path: kubernetes/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: branch-manager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  info:
    - name: 'Environment'
      value: 'Production'
    - name: 'Owner'
      value: 'Platform Team'
    - name: 'Contact'
      value: 'platform@your-domain.com'